### PR TITLE
Fix text overflow in the Reset Info dialog (closes #1299)

### LINKED ISSUE #1299: Reset Info dialog is too small
image

Scrolling is needed, and that obfuscates the somewhat non-trivial message. The dialog should be wider and higher by default 🤔

### PR DESCRIPTION
**Pull request by mkondratek**

### CODE REVIEW

**Review by PawelLipski — COMMENTED** [review]
Once ready for review, pls include the screenshot of the dialog

**Comment by mkondratek** [comment]
image

File: frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/ResetInfoDialog.kt [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+import org.checkerframework.checker.tainting.qual.Tainted
+import java.awt.Dimension
+
+class ResetInfoDialog(project: Project, private val content: @Tainted String) :
+  DialogWrapper(project, /* canBeParent */ true) {
+
+  init {
+    title = getString("action.GitMachete.BaseResetToRemoteAction.info-dialog.title")
+    setOKButtonMnemonic('O'.code)
+    setDoNotAskOption(object : com.intellij.openapi.ui.DoNotAskOption.Adapter() {
```
Comment (PawelLipski) [inline frontend/actions/src/main/kotlin/com/virtuslab/gitmachete/frontend/actions/dialogs/ResetInfoDialog.kt:20]: Actually, _one simple trick_ to avoid instantiating an inner class in c'tor here: create a private method `createDoNotAskOptionAdapter(project: Project)` that will return this very `object`... and then

```suggestion
    setDoNotAskOption(createDoNotAskOptionAdapter(project))
```

Even better, `createDoNotAskOptionAdapter` can be a "static" method (so in Kotlin terms, defined in companion object).

File: src/test/java/com/virtuslab/archunit/ClassStructureTestSuite.java [hunk 2]
```diff
@@ -117,6 +117,8 @@ public void inner_classes_should_not_be_instantiated_from_constructor_of_enclosi
         .that()
         .doNotHaveFullyQualifiedName(com.virtuslab.gitmachete.frontend.actions.dialogs.GitPushDialog.class.getName())
         .and()
+        .doNotHaveFullyQualifiedName(com.virtuslab.gitmachete.frontend.actions.dialogs.ResetInfoDialog.class.getName())
```
Comment (PawelLipski) [inline src/test/java/com/virtuslab/archunit/ClassStructureTestSuite.java:120]: To be removed ☝🏻

**Comment by PawelLipski** [comment]
> image

Are extra newlines possible? I'd add 3 newlines:
1. before `Once you...`
2. before `git reset --keep <hash>`
3. after `git reset --keep <hash>`

**Comment by mkondratek** [comment]
image

File: frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties [hunk 3]
```diff
@@ -114,10 +114,10 @@ action.GitMachete.BaseResetToRemoteAction.info-dialog.title=Git Machete Reset In
 action.GitMachete.BaseResetToRemoteAction.info-dialog.message.HTML=\
   <html>\
     Git Machete Reset will perform a reset of local branch <b>{0}</b> \
-    so that it will point to the same commit as its remote branch <b>{1}</b>. \
+    so that it will point to the same commit as its remote branch <b>{1}</b>.<br><br> \
     Once you perform the action, you will still be able to restore the pre-reset commit. \
-    To achieve that check out <b>{0}</b> and use \
-    <tt>git reset --keep {2}</tt>. \
+    To achieve that check out <b>{0}</b> and use<br><br> \
+    <tt>git reset --keep {2}</tt>.<br><br> \
```
Comment (PawelLipski) [inline frontend/resourcebundles/src/main/resources/GitMacheteBundle.properties:120]:
```suggestion
    <tt>git reset --keep {2}</tt><br><br> \
```

As the period at the end is misleading ;p

**Review by PawelLipski — APPROVED** [review]
