### PR TITLE
Get rid of LOG.error based IDE errors for isBranchPresent calls

### LINKED ISSUE #1298: `GitCoreRepository.isBranchPresent` throws "Not a directory" exception for local branch
Reproduce steps:
1. Create a new local branch in repository `A` (it should not exist remotely - only locally)
2. Open `A` as a project in IntelliJ IDEA
3. Open Machete File
4. Boom! Ide error appears.

In my case - the branch's name was `docs/improve_reference_conf_comments`. This exception looks like a false positive. It should not be displayed as an error.

Stacktrace:
```
java.nio.file.FileSystemException: /Users/lkontowski/code/ide-probe/.git/refs/remotes/upstream/docs/improve_reference_conf_comments: Not a directory
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at org.eclipse.jgit.util.FileUtils.fileAttributes(FileUtils.java:804)
	at org.eclipse.jgit.util.FS.fileAttributes(FS.java:1268)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:234)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:213)
	at org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:104)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.lambda$1(RefDirectory.java:1095)
	at org.eclipse.jgit.util.FileUtils.readWithRetries(FileUtils.java:722)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.scanRef(RefDirectory.java:1094)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.readRef(RefDirectory.java:1052)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.readAndResolve(RefDirectory.java:263)
	at org.eclipse.jgit.internal.storage.file.RefDirectory.firstExactRef(RefDirectory.java:317)
	at org.eclipse.jgit.lib.RefDatabase.findRef(RefDatabase.java:271)
	at org.eclipse.jgit.lib.Repository.findRef(Repository.java:1094)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:811)
	at org.eclipse.jgit.lib.Repository.resolve(Repository.java:472)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$isBranchPresent$3f19b513$1(GitCoreRepository.java:137)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.isBranchPresent(GitCoreRepository.java:137)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveRemoteBranchByName(GitCoreRepository.java:278)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveInferredRemoteBranchForLocalBranch(GitCoreRepository.java:384)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveRemoteBranchForLocalBranch$ff082a48$1(GitCoreRepository.java:353)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveRemoteBranchForLocalBranch(GitCoreRepository.java:353)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveAllLocalBranches$d9482c2f$1(GitCoreRepository.java:309)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.lambda$deriveAllLocalBranches$11(GitCoreRepository.java:298)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.virtuslab.gitcore.impl.jgit.GitCoreRepository.deriveAllLocalBranches(GitCoreRepository.java:313)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$Aux.<init>(GitMacheteRepository.java:124)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository$CreateGitMacheteRepositoryAux.<init>(GitMacheteRepository.java:304)
	at com.virtuslab.gitmachete.backend.impl.GitMacheteRepository.createSnapshotForLayout(GitMacheteRepository.java:80)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.lambda$updateRepositorySnapshot$ebc90931$1(GitMacheteRepositoryUpdateBackgroundable.java:94)
	at io.vavr.control.Try.of(Try.java:75)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.updateRepositorySnapshot(GitMacheteRepositoryUpdateBackgroundable.java:91)
	at com.virtuslab.gitmachete.frontend.ui.impl.table.GitMacheteRepositoryUpdateBackgroundable.run(GitMacheteRepositoryUpdateBackgroundable.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:426)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:667)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by LukaszKontowski**
Closes #1298

### CODE REVIEW

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 1]
```diff
@@ -133,8 +133,22 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
     }
   }
 
-  private boolean isBranchPresent(String branchFullName) {
-    return Try.of(() -> jgitRepoForMainGitDir.resolve(branchFullName)).getOrNull() != null;
+  private boolean isBranchPresent(String branchFullName, String currentlyCheckedBranchFullName) {
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:136]: `currentlyCheckedBranchFullName` is a veeery confusing name, it looks like _currently checked **out** branch name_, which is definitely isn't supposed to be 😅

Comment (PawelLipski) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:136]: Also, I wouldn't expose that param in `isBranchPresent`'s interface.. this looks like a detail of recursive implementation which can be hidden from the callers. What callers care for is just whether `branchFullName` exists

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 2]
```diff
@@ -133,8 +133,22 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
...
+    boolean branchExists = Try.of(() -> jgitRepoForMainGitDir.resolve(currentlyCheckedBranchFullName)).getOrNull() != null;
+    if (branchFullName.equals(currentlyCheckedBranchFullName)) {
+      return branchExists;
+    } else if (branchExists) {
+      return false;
+    } else {
+      @SuppressWarnings("index:argument") String remainingWithoutBeginningSlash = branchFullName
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:143]: Checker's warning here is completely justified, in principle there's no compile-time guarantee that `currentlyCheckedBranchFullName` is shorter than `branchFullName` (and hence, that `branchFullName.substring(currentlyCheckedBranchFullName.length() + 1)` will complete successfully)

Comment (PawelLipski) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:143]: It's a different question whether it can be suppressed (since we know otherwise that `substring` call is correct)... let's assume for now that it can

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 3]
```diff
@@ -286,6 +300,19 @@ private List<IGitCoreReflogEntry> deriveReflogByRefFullName(String refFullName,
     return remoteBranch;
   }
 
+  private String findFirstPossibleBranchNameToCheck(String branchFullName, String branchShortName) {
+    int firstForwardSlashIndexInBranchShortName = branchShortName.indexOf('/');
+    if (firstForwardSlashIndexInBranchShortName == -1) {
+      return branchFullName;
+    } else {
+      @SuppressWarnings("index:argument") String branchesDirectoryName = branchFullName.substring(0,
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:308]: Hmmm looking at the implementation.. I'm not sure whether operating on substrings is the best idea 🤔 it's pretty error-prone and hard to understand TBH. How about switching the the representation of **Vavr List of `/`-separated segments**? You'll then have methods like `take(n)` for taking a prefix with the given number of segments, and `mkString("/")` to join them back before passing to `jgitRepoForMainGitDir.resolve`

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 4]
```diff
@@ -133,8 +133,22 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
     }
   }
 
-  private boolean isBranchPresent(String branchFullName) {
-    return Try.of(() -> jgitRepoForMainGitDir.resolve(branchFullName)).getOrNull() != null;
+  private boolean isBranchPresent(String branchFullName, String currentlyCheckedBranchFullName) {
+    boolean branchExists = Try.of(() -> jgitRepoForMainGitDir.resolve(currentlyCheckedBranchFullName)).getOrNull() != null;
+    if (branchFullName.equals(currentlyCheckedBranchFullName)) {
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:138]: Whatever the implementation ends up like, pls document why this workaround was needed in the first place as it's non-trivial as f**k

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java (hunk 3 above)
Comment (PawelLipski) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:308]: And the entire impl could be sth like

```java
val segments = List.of(branchFullName.split("/"));
for i = 3..segments.length()-1:
  if jgitRepoForMainGitDir.resolve(segments.take(i).mkString("/")):
    return false
return jgitRepoForMainGitDir.resolve(branchFullName)
```

**Comment by LukaszKontowski** [comment]
Replaced _substring based_ solution with usage of Vavr collections helper methods. Also, added a code comment to explain why we need this.

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 5]
```diff
@@ -134,7 +134,30 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
...
+    // .git/refs/remotes/upstream/docs is not a directory). And that will produce a LOG.error which will generate
+    // an IDE error. So, the cause of this while loop is to avoid such IDE errors.
+    val segments = List.of(branchFullName.split("/"));
+    int numOfSegmentsToUse = 3; // 3 is the least number that can contain the branch name (for `refs/heads/<branch_name>`)
+    boolean result = false;
+    while (!result && numOfSegmentsToUse <= segments.size()) {
+      val testedSegment = segments.take(numOfSegmentsToUse).mkString("/");
+      result = Try.of(() -> jgitRepoForMainGitDir.resolve(testedSegment)).getOrNull() != null;
+      numOfSegmentsToUse++;
+    }
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:154]: How about sth like
```suggestion
     // 3 is the least number that can contain the branch name (for `refs/heads/<branch_name>`)
    for (int numOfSegmentsToUse = 3; numOfSegmentsToUse < segments.size(); numOfSegmentsToUse++) {
      val testedPrefix = segments.take(numOfSegmentsToUse).mkString("/");
      if (Try.of(() -> jgitRepoForMainGitDir.resolve(testedSegment)).getOrNull() != null)
        return false;
    }
    
```

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 6]
```diff
@@ -134,7 +134,30 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
...
+
+    if (numOfSegmentsToUse > segments.size()) { // which means the last checked `testedSegment` was `branchFullName`
+      return result;
+    } else { // which means existing branch was found for a `testedSegment` that was a part of the `branchFullName`
+      return !result; // if branch `foo` is present, then branch `foo/bar` will not be present under the same directory
+    }
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:160]: ...and then

```suggestion
    return Try.of(() -> jgitRepoForMainGitDir.resolve(branchFullName)).getOrNull() != null;
```

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 7]
```diff
@@ -134,7 +134,30 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
...
-    return Try.of(() -> jgitRepoForMainGitDir.resolve(branchFullName)).getOrNull() != null;
+    // If '/' chars exist in the branch name, then this loop is needed in order to avoid possible IDE errors, which
+    // could appear if two files like in the example below exist under .git directory for the repository:
+    // .git/refs/heads/docs/improve_readme (short branch name is `docs/improve_readme` - exists locally)
+    // .git/refs/remotes/upstream/docs (short branch name is `docs` - this branch exists only on upstream, not locally)
+    // In such scenario `org.eclipse.jgit.lib.Repository#resolve` called to check if `docs/improve_readme` branch exists
+    // under .git/refs/remotes/upstream/ will try to find the branch using the following file path:
+    // .git/refs/remotes/upstream/docs/improve_readme
+    // which will end in a "Not a directory" `java.nio.file.FileSystemException` (as existing file
+    // .git/refs/remotes/upstream/docs is not a directory). And that will produce a LOG.error which will generate
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:145]: Pls refer to the specific method that calls `LOG.error`, also mention that the problem is with `org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)`, not `org.slf4j.Logger#error(java.lang.String)`

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 8]
```diff
@@ -134,7 +134,32 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
   }
 
   private boolean isBranchPresent(String branchFullName) {
-    return Try.of(() -> jgitRepoForMainGitDir.resolve(branchFullName)).getOrNull() != null;
+    // If '/' chars exist in the branch name, then this loop-based testing is needed in order to avoid possible IDE errors,
```
Comment (mkondratek) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:137]: I would rather move this comment onto the method. That will allow us to make it a javadoc and actually reference classes and methods (and gives more flexibility in the scope of formatting IIRC).

Comment (mkondratek) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:137]: `s/chars/characters/g`

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 9]
```diff
@@ -134,7 +134,32 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
...
+    // .git/refs/heads/docs/improve_readme (short branch name is `docs/improve_readme` - exists locally)
+    // .git/refs/remotes/upstream/docs (short branch name is `docs` - this branch exists only on upstream, not locally)
+    // In such scenario `org.eclipse.jgit.lib.Repository#resolve` called to check if `docs/improve_readme` branch exists
+    // under .git/refs/remotes/upstream/ will try to find the branch using the following file path:
+    // .git/refs/remotes/upstream/docs/improve_readme
+    // which will end in a "Not a directory" `java.nio.file.FileSystemException`, as existing file
+    // .git/refs/remotes/upstream/docs is not a directory. And that will produce a `LOG.error` -
+    // `org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)` called from within
+    // `org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>`. And it will generate an IDE error.
+    // So, the cause of this loop-based testing is to avoid such IDE errors.
```
Comment (mkondratek) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:148]: very nice explanation! 👏

**Review by mkondratek — CHANGES_REQUESTED** [review]

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java (hunk 8 above)
Comment (PawelLipski) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:137]: Although... this entire comment isn't relevant in terms of method interface, it's an implementation detail 🤔

Comment (mkondratek) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:137]: I would rather...  for the sake of the other methods/classes refs and better formatting (HTML). but no strong feelings about it

**Review by mkondratek — APPROVED** [review]
I will not block it xd

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 10]
```diff
@@ -134,7 +134,30 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
   }
 
   private boolean isBranchPresent(String branchFullName) {
-    return Try.of(() -> jgitRepoForMainGitDir.resolve(branchFullName)).getOrNull() != null;
+    // If '/' chars exist in the branch name, then this loop is needed in order to avoid possible IDE errors, which
+    // could appear if two files like in the example below exist under .git directory for the repository:
+    // .git/refs/heads/docs/improve_readme (short branch name is `docs/improve_readme` - exists locally)
```
[the remark this answers is not in the document]
Comment (PawelLipski) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:139]: It isn't possible to create both `refs/heads/foo` and `refs/heads/foo/bar` indeed... but IIUC the problem with `LOG.error` will still happen if you only have `refs/heads/foo` and ask for `refs/heads/foo/bar`? Regardless of whether `deriveRemoteBranchByName` or `deriveLocalBranchByName` will ever make such a call, let's just consider `isBranchPresent` in isolation.

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java (hunk 5 above)
Comment (PawelLipski) [reply gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java]: > prematurely breaking the loop and returning something for the whole method in the middle of the loop.

That's a perfectly valid idiom, esp. in Java :) See e.g. `io.vavr.collection.LinearSeq#indexWhere`, just first example that I've found

File: gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java [hunk 11]
```diff
@@ -134,6 +134,39 @@ private <T> T withRevWalkUnchecked(CheckedFunction1<RevWalk, T> fun) {
...
+    // .git/refs/heads/foo/bar
+    // which will end in an IDE error with a "Not a directory" `java.nio.file.FileSystemException`.
+    // Explanation:
+    // 1) One of the classes used by `org.eclipse.jgit` to resolve the git branch is
+    //   `org.eclipse.jgit.internal.storage.file.FileSnapshot`.
+    // 2) `org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>` called to find if .git/refs/heads/foo/bar exists
+    //    will try to resolve this path, which will produce "Not a directory" `java.nio.file.FileSystemException`,
+    //    because file .git/refs/heads/foo (part of the resolved path) is NOT a directory.
+    // 3) Catching `FileSystemException` will produce a `LOG.error` - `org.slf4j.Logger#error(java.lang.String, java.lang.Throwable)`
+    // 4) `LOG.error` will generate an IDE error.
```
Comment (PawelLipski) [inline gitCore/jGit/src/main/java/com/virtuslab/gitcore/impl/jgit/GitCoreRepository.java:153]:
```suggestion
    // 4) `LOG.error` will generate an IDE error. Note that is would NOT happen if `org.slf4j.Logger#error(java.lang.String)` was called instead.
```

**Review by PawelLipski — APPROVED** [review]
