### PR TITLE
Fix too long string (closes #1198)

### LINKED ISSUE #1198: The text of `Cannot pull anymore` notification is truncated, no way to expand
image

To be researched whether there are other places that are (potentially) affected by the same problem. Ideally, to be prevented automatically somehow 😅

### PR DESCRIPTION
**Pull request by mkondratek**
The lesson from this one - keep titles short. The detailed info should be kept in the notification content.

pull non-current with fetch:
image

pull non-current without fetch:
image

pull non-current with fetch - fail:
image

pull non-current without fetch - fail:
image

### CODE REVIEW

**Comment by mkondratek** [comment]
foo

File: frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/backgroundables/CheckRemoteBranchBackgroundable.java [hunk 1]
```diff
@@ -9,25 +9,30 @@
...
 import com.virtuslab.qual.guieffect.UIThreadUnsafe;
 
+@ExtensionMethod(GitMacheteBundle.class)
 public class CheckRemoteBranchBackgroundable extends Task.Backgroundable {
 
   private final Project project;
   private final GitRepository gitRepository;
   private final String remoteBranchName;
-  private final String taskFailNotification;
+  private final String taskFailNotificationTitle;
```
Comment (mkondratek) [inline frontend/actions/src/main/java/com/virtuslab/gitmachete/frontend/actions/backgroundables/CheckRemoteBranchBackgroundable.java:25]: good idea

**Review by mkondratek — COMMENTED** [review]
test

**Review by PawelLipski — APPROVED** [review]
:fantastycznie:
