### PR TITLE
Fix the error submitter issue title

### LINKED ISSUE #1223: Issues opened via error submitter have `com.intellij.diagnostic.IdeaReportingEvent$TextBasedThrowable` as title
See #1215. I'd rather expect sth like `java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.isDirectory()" because "file" is null` as the title.

FWIW, I did some quick debug on branch `debug/1215-submitter-title` but reached no conclusion. I can't see where the `TextBasedThrowable` is even coming from 🤔 

As a part of this task, add a test that would've capture the issue.

### PR DESCRIPTION
**Pull request by LukaszKontowski**
Closes #1223

### CODE REVIEW

File: frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java [hunk 1]
```diff
@@ -58,7 +58,8 @@ URI constructNewGitHubIssueUri(IdeaLoggingEvent[] events, @Nullable String addit
     String title = events.stream()
         .map(event -> {
           val throwable = event.getThrowable();
-          return (throwable != null ? throwable.toString() : event.getMessage()).stripTrailing();
+          val exceptionMessage = event.getThrowableText().split(System.lineSeparator())[0];
```
Comment (PawelLipski) [inline frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java:61]: Hmmm actually one thing... where does this first line of `event.getThrowableText()` ultimately come from? I.e. how is that different from whatever `throwable.toString()` returns? 🤔

Comment (LukaszKontowski) [reply frontend/ui/impl/src/main/java/com/virtuslab/gitmachete/frontend/ui/impl/GitMacheteErrorReportSubmitter.java:61]: `throwable.toString()` always evaluates to just:
"com.intellij.diagnostic.IdeaReportingEvent$TextBasedThrowable"

whereas

`event.getThrowableText()` returns the whole stack trace - example from my tests:
```
java.lang.RuntimeException: Test message - this is the first line that gets printed (used in Exception constructor)
	at com.virtuslab.gitmachete.frontend.actions.toolbar.OpenMacheteFileAction.actionPerformed(OpenMacheteFileAction.java:75)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:197)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:173)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:341)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:471)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:915)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:775)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:445)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:443)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:489)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

So, the first line would be 
"java.lang.RuntimeException: Test message - this is the first line that gets printed (used in Exception constructor)"

**Review by PawelLipski — APPROVED** [review]
