### PR TITLE
Fix graph scaling (closes #626)

### LINKED ISSUE #626: Graph does not scale along with font size

### PR DESCRIPTION
**Pull request by mkondratek**

### CODE REVIEW

File: frontendGraphImpl/src/main/java/com/virtuslab/gitmachete/frontend/graph/impl/paint/GraphCellPainter.java [hunk 1]
```diff
@@ -29,7 +29,12 @@
 
   @UIEffect
   protected int getRowHeight() {
-    return table.getRowHeight();
+    var font = table.getFont();
```
Comment (PawelLipski) [inline frontendGraphImpl/src/main/java/com/virtuslab/gitmachete/frontend/graph/impl/paint/GraphCellPainter.java:32]: Pls add a comment in the code:
1. when (semantically) the font is null and when not (if we know that)
2. that the purpose is to make graph scale alongside the default font from IntelliJ Settings

**Comment by PawelLipski** [comment]
Tested locally, works fine for me:

image

**Review by PawelLipski — APPROVED** [review]

**Review by PawelLipski — APPROVED** [review]

**Comment by PawelLipski** [comment]
@mkondratek pls bump version.gradle to 0.8.1
